---
apiVersion: v1
kind: Pod
metadata:
  name: shape-publisher
  labels:
    app: shape-publisher
spec:
  containers:
    - name: shape-publisher
      image: centos-1:5000/shape-publisher:latest
      ports:
        - containerPort: 7400
          protocol: "UDP"
          name: "rtps2-disc-mult"
        - containerPort: 7401
          protocol: "UDP"
          name: "rtps2-disc-uni"
        - containerPort: 7410
          protocol: "UDP"
          name: "rtps2-data-mult"
        - containerPort: 7411
          protocol: "UDP"
          name: "rtps2-data-uni"
  imagePullSecrets:
    - name: docker-registry-centos-1
  restartPolicy: Always
