---
# ------------------------------------------------------------------------------
- hosts: centos
  roles:
    - { role: ntp }
    - { role: disable-selinux }
    - { role: disable-firewall }
    - { role: weave/kube/main, weave_group: "centos" }
    - { role: kubernetes/main }

# ------------------------------------------------------------------------------
- hosts: master
  roles:
    - { role: scope/kubernetes/main }
...
