---
# ------------------------------------------------------------------------------
- name: stop
  command: "docker -H tcp://{{ groups['master'][0] }}:2400 rm -f rti-perftest-pub-{{ item }}"
  with_sequence: start=1 end={{ groups['master'] | length }}
