---
# ------------------------------------------------------------------------------
- name: stop
  command: "docker -H tcp://{{ groups['master'][0] }}:2400 rm -f rti-perftest-pub-{{ inventory_hostname | checksum }}"
...
