---
- name: copy key
  copy:
    src: ".ssh/ansible"
    dest: "~/.ssh/id_rsa"
    mode: 0600

- name: copy public key
  copy:
    src: ".ssh/ansible.pub"
    dest: "~/.ssh/id_rsa.pub"
    mode: 0600
