---
- name: "service account : check"
  shell: >
    /usr/bin/kubectl --kubeconfig=/etc/kubernetes/admin.conf \
      --namespace=kube-system \
      --no-headers=true \
      get serviceaccount \
      tiller | wc -l
  changed_when: no
  register: helm_init_check_service_account

- name: "service account : create"
  command: >
    /usr/bin/kubectl --kubeconfig=/etc/kubernetes/admin.conf
      --namespace kube-system
      create serviceaccount
      tiller
  when: helm_init_check_service_account.stdout | int == 0

- name: "cluster role binding : check"
  shell: >
    /usr/bin/kubectl --kubeconfig=/etc/kubernetes/admin.conf \
      --namespace=kube-system \
      --no-headers=true \
      get clusterrolebinding \
      tiller | wc -l
  changed_when: no
  register: helm_init_check_cluster_role_binding

- name: "cluster role binding : create"
  command: >
    /usr/bin/kubectl --kubeconfig=/etc/kubernetes/admin.conf
      create clusterrolebinding
      tiller
      --clusterrole=cluster-admin
      --serviceaccount=kube-system:tiller
  when: helm_init_check_cluster_role_binding.stdout | int == 0

- name: "tiller : check"
  shell: >
    /usr/bin/kubectl --kubeconfig=/etc/kubernetes/admin.conf \
      --namespace=kube-system \
      --no-headers=true \
      get pod \
      --selector app=helm,name=tiller | wc -l
  changed_when: no
  register: helm_init_check_tiller

- name: "tiller : init"
  shell: "/usr/bin/helm init --kubeconfig=/etc/kubernetes/admin.conf --service-account tiller {% if helm_init_check_tiller.stdout | int > 0 -%}--upgrade{%- endif %} --wait"
  environment:
    HELM_HOME: "{{ helm_user_home }}/.helm"

- name: set permissions
  file:
    path: "{{ helm_user_home }}/.helm"
    recurse: yes
    owner: "{{ helm_user }}"
    group: "{{ helm_user }}"
