---
# ------------------------------------------------------------------------------
- hosts: centos
  roles:
    - { role: chrony }
    - { role: disable-selinux }
    - { role: disable-firewall }

# ------------------------------------------------------------------------------
- hosts: centos
  roles:
    - { role: kubernetes/el7 }
    - { role: weave/kube/el7, weave_group: "nodes" }
    - { role: cockpit }
