---
# ------------------------------------------------------------------------------
- hosts: centos
  roles:
    - ntp
    - disable-selinux
    - disable-firewall

# ------------------------------------------------------------------------------
- hosts: master
  roles:
    - kubernetes.el7.master

# ------------------------------------------------------------------------------
- hosts: nodes
  roles:
    - kubernetes.el7.node
    - weave-kubernetes.el7

# ------------------------------------------------------------------------------
- hosts: centos
  roles:
    - cockpit
...
