---
# ------------------------------------------------------------------------------
- hosts: centos
  roles:
    - { role: ntp }
    - { role: disable-selinux }
    - { role: disable-firewall }

# ------------------------------------------------------------------------------
- hosts: master
  roles:
    - { role: kubernetes/el7 }

# ------------------------------------------------------------------------------
- hosts: nodes
  roles:
    - { role: kubernetes/el7 }
    #- { role: weave/kube/el7, weave_group: "nodes" }

# ------------------------------------------------------------------------------
- hosts: centos
  roles:
    - { role: cockpit }
