---
# ------------------------------------------------------------------------------
- hosts: centos
  roles:
    - chrony
    - disable-selinux
    - disable-firewall

# ------------------------------------------------------------------------------
- hosts: centos
  vars:
    - weave_group: "nodes"
  roles:
    - kubernetes/el7
    - weave/kube/el7
    - cockpit
