---
# ------------------------------------------------------------------------------
- hosts: centos
  roles:
    - { role: ntp }
    - { role: disable-selinux }
    - { role: disable-firewall }
    - { role: docker/el7 }
    - { role: cockpit }

# ------------------------------------------------------------------------------
- hosts: centos
  roles:
    - { role: nomad, nomad_group: "centos" }
