= containers-rti
Repository to test RTI Connext DDS with container technologies (docker, kubernetes).

== Environment
Vagrant can be used to deploy the necessary virtual machines.

In the default configuration you will get 3 VMs where the first is in the master group and the other two in the nodes group:

[width="20%", cols="1,1a,1", options="header"]
|===
| Host | Groups | Private IP

| centos-1
| * centos
  * master
| 172.30.0.11/24

| centos-2
| * centos
  * nodes
| 172.30.0.12/24

| centos-3
| * centos
  * nodes
| 172.30.0.13/24
|===

=== Proxy Configuration
If applicable, using a proxy is possible directly via proxy address inside the virtual machines.

[NOTE]
The proxy must be reachable inside the VM to work properly.

Take the following steps to configure the virtual machines for a proxy address.
[source,bash]
----
export VM_PROXY=http://proxy.domain:8080/
----

=== Initialization
Thanks to vagrant the deployment of the virtual machines is really easy. The configuration can be found in the file `Vagrantfile`. It's possible to change the number of virtual machines and the playbook used during provisioning via environment variables (see below).

The virtual machines can be deployed with the following commands:
[source,bash]
----
./vagrant-deploy.sh --help
./vagrant-deploy.sh --instances=4 --cpu=3 --memory=4096 --playbook=deploy-kubernetes.yml
----

=== Execution of additional playbooks after provisioning
[source,bash]
----
./vagrant-playbook.sh <playbook>
----

=== Shutdown
[source,bash]
----
vagrant halt
----

=== Startup
[source,bash]
----
vagrant up
----

=== Destroy
[source,bash]
----
vagrant destroy -f
----


== Docker
In this scenario the rti-perftest example will be executed on single hosts with Docker installed which is available in the extras-repository.
Weave-Net is used to connect the containers on the different hosts.

=== Start
[source,bash]
----
./vagrant-deploy.sh --playbook=deploy-docker-weave.yml
./vagrant-playbook.sh rti-perftest-docker-start.yml
----

=== Stop
[source,bash]
----
./vagrant-playbook.sh rti-perftest-docker-stop.yml
----

=== Monitoring
Monitoring can be done using the tool cockpit which can be reached on the address `http://<host>:9090`.


== Kubernetes
In this scenario the rti-perftest example will be executed on a Kubernetes cluster which is available in the extras-repository.

Weave-Net is used to connect the containers on the different hosts. A network policy is deployed that isolates a pair of publishers/subscribers based on a id. The id is per default 1 but can be changed via Ansible variable (see below).

=== General

==== Monitoring
Monitoring can be done using the Kubernetes Dashboard UI. It can be reached on the address `http://<host>:30000`. Additionally you can also access the tool cockpit which can be reached on the address `http://<host>:9090`.

Grafana can be accessed (sometimes has issue with the URL):
[source,bash]
----
vagrant ssh -c "kubectl proxy --address=172.30.0.11 --accept-hosts=.*"
http://172.30.0.11:8001/api/v1/namespaces/kube-system/services/http:monitoring-grafana:80/proxy
----

=== rook-cluster
[source,bash]
----
./vagrant-playbook.sh kubernetes-rook-cluster.yml
----

=== rti-perftest

==== Start
[source,bash]
----
./vagrant-deploy.sh
./vagrant-playbook.sh -e rti_perftest_id=1 -e rti_perftest_sub_count=2 rti-perftest-kubernetes-start.yml
----

==== Stop
[source,bash]
----
./vagrant-playbook.sh -e rti_perftest_id=1 -e rti_perftest_sub_count=2 rti-perftest-kubernetes-stop.yml
----

=== rti-shapes-demo

In order to start this example, you need to put the following docker images into directory `docker-images`:

* `dds-examples--latest.tar.gz`
* `rti-cloud-discovery-service--5.3.1.tar.gz`
* `rti-persistence-service--5.3.1.tar.gz`
* `rti-routing-service--5.3.1.tar.gz`

==== Start
[source,bash]
----
# load docker images
./vagrant-playbook.sh load-docker-images.yml

# install helm chart for rti-shapes-demo
./vagrant-playbook.sh rti-shapes-demo.yml
----

==== Stop
[source,bash]
----
# stop rti-shapes-demo
vagrant ssh -c "helm delete $(helm ls | awk '/rti-shapes-demo/ { print $1 }')"
----


== Nomad
In this scenario the rti-perftest example will be executed on a Nomad cluster using the Docker driver.

=== Start
[source,bash]
----
./vagrant-deploy.sh --playbook=deploy-nomad.yml
./vagrant-playbook.sh rti-perftest-nomad-start.yml
----

=== Stop
[source,bash]
----
./vagrant-playbook.sh rti-perftest-nomad-stop.yml
----

=== Monitoring
Monitoring can be done using the tool cockpit which can be reached on the address `http://<host>:9090`. Additionally the nomad status can be checked with:
[source,bash]
----
vagrant ssh -c "nomad status"
----


== Links
* https://www.vagrantup.com[Vagrant]
* https://www.docker.io[Docker]
* https://www.kubernetes.io[Kubernetes]
* https://www.weave.works/products/weave-net[Weave-Net]
* https://www.weave.works/products/weave-scope[Weave-Scope]
* https://access.redhat.com/articles/2317361[Introducing docker-latest for RHEL 7 and RHEL Atomic Host]
* https://severalnines.com/blog/installing-kubernetes-cluster-minions-centos7-manage-pods-services[Installing Kubernetes Cluster with 3 minions on CentOS 7 to manage pods and services]
