= containers-rti
Repository to test RTI DDS with container technologies (docker, kubernetes).

== Environment
Vagrant can be used to deploy the necessary virtual machines.

In the default configuration you will get 3 VMs where the first is in the master group and the other two in the nodes group:

[width="20%", cols="1,1a,1", options="header"]
|===
| Host | Groups | Private IP

| centos-1
| * centos
  * master
| 172.30.0.11/24

| centos-2
| * centos
  * nodes
| 172.30.0.12/24

| centos-3
| * centos
  * nodes
| 172.30.0.13/24
|===

=== Proxy Configuration
If applicable, using a proxy is possible directly via proxy address inside the virtual machines.

Take the following steps to configure the virtual machines for an proxy address.
[source,bash]
----
export VM_PROXY=http://proxy.domain:8080/
----

=== Initialization
Thanks to vagrant the deployment of the virtual machines is really easy. The configuration can be found in the file `Vagrantfile`. It's possible to change the number of virtual machines and the playbook used during provisioning via environment variables (see below).

The virtual machines can be deploying with the following commands:
[source,bash]
----
= optional, default = 3
export VM_INSTANCES=4
= optional, default = none
export PLAYBOOK=deploy-kubernetes.yml
vagrant up
----

=== Execution of additional playbooks after provisioning
[source,bash]
----
vagrant ssh -c "cd /vagrant; ansible-playbook -i /tmp/vagrant-ansible/inventory/vagrant_ansible_local_inventory <playbook>"
----

=== Shutdown
[source,bash]
----
vagrant halt
----

=== Destroy
[source,bash]
----
vagrant destroy -f
----


== Docker
In this scenario the rti-perftest example will be executed on single hosts with Docker installed which is available in the extras-repository.
Weave-Net is used to connect the containers on the different hosts.

=== Start
[source,bash]
----
export PLAYBOOK=deploy-docker-weave.yml
vagrant destroy -f
vagrant up
vagrant ssh -c "cd /vagrant; ansible-playbook -i /tmp/vagrant-ansible/inventory/vagrant_ansible_local_inventory rti-perftest-docker-start.yml"
----

=== Stop
[source,bash]
----
vagrant ssh -c "cd /vagrant; ansible-playbook -i /tmp/vagrant-ansible/inventory/vagrant_ansible_local_inventory rti-perftest-docker-stop.yml"
----

=== Monitoring
Monitoring can be done using the tool cockpit which can be reached on the address `http://<host>:9090`.


== Kubernetes
In this scenario the rti-perftest example will be executed on a Kubernetes cluster which is available in the extras-repository.
Weave-Net is used to connect the containers on the different hosts.

=== Start
[source,bash]
----
export PLAYBOOK=deploy-kubernetes.yml
vagrant destroy -f
vagrant up
vagrant ssh -c "cd /vagrant; ansible-playbook -i /tmp/vagrant-ansible/inventory/vagrant_ansible_local_inventory rti-perftest-kubernetes-start.yml"
----

=== Stop
[source,bash]
----
vagrant ssh -c "cd /vagrant; ansible-playbook -i /tmp/vagrant-ansible/inventory/vagrant_ansible_local_inventory rti-perftest-kubernetes-stop.yml"
----

=== Monitoring
Monitoring can be done using the tool cockpit which can be reached on the address `http://<host>:9090`. It also supports Kubernetes and can be reached with the tab 'Cluster'.


== Nomad
In this scenario the rti-perftest example will be executed on a Nomad cluster using the Docker driver.

=== Start
[source,bash]
----
export PLAYBOOK=deploy-nomad.yml
vagrant destroy -f
vagrant up
vagrant ssh -c "cd /vagrant; ansible-playbook -i /tmp/vagrant-ansible/inventory/vagrant_ansible_local_inventory rti-perftest-nomad-start.yml"
----

=== Stop
[source,bash]
----
vagrant ssh -c "cd /vagrant; ansible-playbook -i /tmp/vagrant-ansible/inventory/vagrant_ansible_local_inventory rti-perftest-nomad-stop.yml"
----

=== Monitoring
Monitoring can be done using the tool cockpit which can be reached on the address `http://<host>:9090`. Additionally the nomad status can be checked with:
[source,bash]
----
vagrant ssh -c "nomad status"
----


== Links
* https://www.vagrantup.com[Vagrant]
* https://www.docker.io[Docker]
* https://www.kubernetes.io[Kubernetes]
* https://www.weave.works/products/weave-net[Weave-Net]
* https://www.weave.works/products/weave-scope[Weave-Scope]
* https://access.redhat.com/articles/2317361[Introducing docker-latest for RHEL 7 and RHEL Atomic Host]
* https://severalnines.com/blog/installing-kubernetes-cluster-minions-centos7-manage-pods-services[Installing Kubernetes Cluster with 3 minions on CentOS 7 to manage pods and services]
