---
# ------------------------------------------------------------------------------
- hosts: master
  roles:
    - rti-perftest-docker/stop-publisher
# ------------------------------------------------------------------------------
- hosts: nodes
  roles:
    - rti-perftest-docker/stop-subscriber
...
