Vagrant.configure("2") do |config|
  # ssh configuration
  config.ssh.insert_key = false
  config.ssh.username = 'vagrant'

  # define machines
  machines = ["1", "2", "3"]
  count = machines.size

  # disable synced folder (causes problems on windows due to missing rsync)
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # customize virtual machine
  config.vm.provider "virtualbox" do |vbox, override|
    vbox.cpus = 2
    vbox.memory = 4096
  end
  # customize virtual machine
  config.vm.provider "vmware_workstation" do |vmware, override|
    vmware.vmx["numvcpus"] = "2"
    vmware.vmx["memsize"] = "4096"
  end

  # provision of virtual machines
  machines.each do |machine_id|
    config.vm.define "centos-7-#{machine_id}" do |machine|
      machine.vm.hostname = "centos-7-#{machine_id}"
      machine.vm.box = "centos/7"
    end
  end

end
