---
# ------------------------------------------------------------------------------
- name: stop and disable firewall
  service:
    name: firewalld.service
    state: stopped
    enabled: false
...
