---
- name: create temporary directory
  tempfile:
    state: directory
    suffix: metallb
  register: metallb_temp_directory

- name: "create configuration : layer 2"
  template:
    src: layer-2.yaml.j2
    dest: "{{ metallb_temp_directory.path }}/ansible_metallb_configuration.yaml"
  when: metallb_mode == "layer-2"

- name: "create configuration : bgp"
  template:
    src: bgp.yaml.j2
    dest: "{{ metallb_temp_directory.path }}/ansible_metallb_configuration.yaml"
  when: metallb_mode == "bgp"

- name: deploy metallb using helm/install
  include_role:
      name: helm/install-chart
  vars:
    helm_install_namespace: metallb
    helm_install_name: metallb
    helm_install_chart: "stable/metallb"
    helm_install_value_files:
      - "{{ metallb_temp_directory.path }}/ansible_metallb_configuration.yaml"

- name: delete temporary directory
  file:
    state: absent
    path: "{{ metallb_temp_directory.path }}"
