---
- name: "create etcd-server"
  command: >
    /usr/bin/kubeadm alpha phase certs etcd-server
      --config=/tmp/etcd-kubeadm.yml
  args:
    creates: /etc/kubernetes/pki/etcd/server.*

- name: "create etcd-peer"
  command: >
    /usr/bin/kubeadm alpha phase certs etcd-peer
      --config=/tmp/etcd-kubeadm.yml
  args:
    creates: /etc/kubernetes/pki/etcd/peer.*

- name: "create etcd-healthcheck-client"
  command: >
    /usr/bin/kubeadm alpha phase certs etcd-healthcheck-client
      --config=/tmp/etcd-kubeadm.yml
  args:
    creates: /etc/kubernetes/pki/etcd/healthcheck-client.*

- name: "create apiserver-etcd-client"
  command: >
    /usr/bin/kubeadm alpha phase certs apiserver-etcd-client
      --config=/tmp/etcd-kubeadm.yml
  args:
    creates: /etc/kubernetes/pki/apiserver-etcd-client.*

- name: "correct permissions"
  file:
    dest: "/etc/kubernetes/pki/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - apiserver-etcd-client.crt
    - apiserver-etcd-client.key
    - etcd/ca.crt
    - etcd/ca.key
    - etcd/healthcheck-client.crt
    - etcd/healthcheck-client.key
    - etcd/peer.crt
    - etcd/peer.key
    - etcd/server.crt
    - etcd/server.key
