---
- name: "check certificates"
  stat:
    path: "/etc/kubernetes/pki/{{item }}"
  with_items:
    - apiserver-etcd-client.crt
    - apiserver-etcd-client.key
    - etcd/ca.crt
    - etcd/ca.key
    - etcd/healthcheck-client.crt
    - etcd/healthcheck-client.key
    - etcd/peer.crt
    - etcd/peer.key
    - etcd/server.crt
    - etcd/server.key
  register: etcd_check_certificates

- name: "set fact"
  set_fact:
    etcd_certificate_missing: yes
  when: not (item.stat.exists)
  loop: "{{ etcd_check_certificates.results }}"

- include_tasks: pki-config-create.yml
  when: etcd_certificate_missing

- include_tasks: pki-create-root.yml
  when: etcd_certificate_missing

- include_tasks: pki-distribute.yml
  when: etcd_certificate_missing
        or (inventory_hostname == groups['master'][0])

- include_tasks: pki-create-client.yml
  when: etcd_certificate_missing

- include_tasks: pki-config-delete.yml
  when: etcd_certificate_missing
