---
- name: "network policy : create definition file"
  template:
    src: rti-perftest-network-policy.yml.j2
    dest: "/tmp/rti-perftest-network-policy.yml"

- name: "network policy : apply"
  command: "/usr/bin/kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /tmp/rti-perftest-network-policy.yml"

- name: "network policy : delete definition file"
  file:
    path: /tmp/rti-perftest-network-policy.yml
    state: absent
