---
# ------------------------------------------------------------------------------
- name: remove packages
  yum:
    name:
      - cockpit
      - cockpit-networkmanager
      - cockpit-storaged
      - cockpit-ws
      - cockpit-shell
      - cockpit-bridge
    state: removed
