---
- name: "keepalived : install"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - keepalived

- name: "keepalived : configuration"
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: 0644
  register: kubernetes_keepalived_configuration

- name: "keepalived : service : restart"
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - keepalived.service
  when: kubernetes_keepalived_configuration.changed

- name: "keepalived : service : enable and start"
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - keepalived.service
