---
# ------------------------------------------------------------------------------
- name: install
  yum:
    name: kubernetes
    state: latest

# ------------------------------------------------------------------------------
- name: set KUBE_MASTER
  command: "sed -i 's/\\(KUBE_MASTER=\"--master=\\).*\\(\"\\)/\\1{{ item }}\\2/g' /etc/kubernetes/config"
  with_items: "http:\\/\\/{{ groups['master'][0] }}:8080"

# ------------------------------------------------------------------------------
- name: set KUBE_API_ADDRESS
  command: "sed -i 's/\\(KUBE_API_ADDRESS=\"--insecure-bind-address=\\).*\\(\"\\)/\\1{{ item }}\\2/g' /etc/kubernetes/apiserver"
  with_items: "0.0.0.0"

- name: comment out KUBE_ADMISSION_CONTROL
  command: "sed -i 's/\\(KUBE_ADMISSION_CONTROL=\"\\)\\(.*\\)\\(\"\\)/#\\1\\2\\3/g' /etc/kubernetes/apiserver"

# ------------------------------------------------------------------------------
- name: enable and start services
  service:
    name: "{{ item }}"
    state: running
    enabled: yes
  with_items:
    - kube-apiserver.service
    - kube-controller-manager.service
    - kube-scheduler.service
...
