---
- name: check if created
  command: >
    /usr/bin/kubectl --kubeconfig=/etc/kubernetes/admin.conf
    get secret docker-registry-tls
      --namespace=docker-registry
  changed_when: no
  failed_when: no
  register: docker_registry_check_tls_secret

- name: create tls secret
  command: >
    /usr/bin/kubectl --kubeconfig=/etc/kubernetes/admin.conf
    create secret tls docker-registry-tls
      --namespace=docker-registry
      --cert={{ docker_registry_storage_certs }}/{{ docker_registry_certificate_host_filename }}.crt
      --key={{ docker_registry_storage_certs }}/{{ docker_registry_certificate_host_filename }}.key
  when: (docker_registry_check_tls_secret.rc != 0)
