---
- name: install packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - yum-versionlock

- name: lock version
  command: "yum versionlock add kubeadm kubectl kubelet"
  args:
    warn: no
