---
- name: "kubeadm : get version"
  command: "/usr/bin/kubeadm version --output short"
  register: kubernetes_kubeadm_get_version

- name: "kubeadm : set version fact"
  set_fact:
    kubernetes_kubeadm_version: "{{ kubernetes_kubeadm_get_version.stdout }}"
  when: kubernetes_kubeadm_get_version.stdout | regex_search('^v\d+.\d+.\d+$')

- name: "kubeadm : configuration"
  template:
    src: kubeadm-config.yml.j2
    dest: /tmp/kubeadm-config.yml
    owner: root
    group: root
    mode: 0644

- name: "kubeadm : init"
  command: /usr/bin/kubeadm init --config /tmp/kubeadm-config.yml

- name: "kubectl : allow users to read configuration"
  file:
    path: /etc/kubernetes/admin.conf
    mode: 0644

- name: "kubectl : setup environment"
  copy:
    src: kubernetes.sh
    dest: /etc/profile.d/kubernetes.sh

- name: "kubeadm : clean up"
  file:
    dest: /tmp/kubeadm-config.yml
    state: absent

- name: "node : remove master taint"
  command: >
    /usr/bin/kubectl --kubeconfig=/etc/kubernetes/admin.conf
      taint nodes
      {{ inventory_hostname }}
      node-role.kubernetes.io/master-
