---
- name: "kubeadm : get version"
  command: "/usr/bin/kubeadm version --output short"
  register: kubernetes_kubeadm_get_version

- name: "kubeadm : set version fact"
  set_fact:
    kubernetes_kubeadm_version: "{{ kubernetes_kubeadm_get_version.stdout }}"
  when: kubernetes_kubeadm_get_version.stdout | regex_search('^v\d+.\d+.\d+$')

- name: "kubeadm : copy configuration"
  template:
    src: kubeadm-config.yml.j2
    dest: /tmp/kubeadm-config.yml
    owner: root
    group: root
    mode: 0644

- name: "kubeadm : certs all"
  command: /usr/bin/kubeadm alpha phase certs all --config /tmp/kubeadm-config.yml

- name: "kubelet : write config"
  command: /usr/bin/kubeadm alpha phase kubelet config write-to-disk --config /tmp/kubeadm-config.yml

- name: "kubelet : write environment file"
  command: /usr/bin/kubeadm alpha phase kubelet write-env-file --config /tmp/kubeadm-config.yml

- name: "kubelet : kubeconfig"
  command: /usr/bin/kubeadm alpha phase kubeconfig kubelet --config /tmp/kubeadm-config.yml

- name: "kubelet : (re)start and enable"
  service:
    name: "kubelet.service"
    state: restarted
    enabled: yes

- name: "etcd : add member to cluster"
  command: >
    /usr/bin/kubectl exec
      --kubeconfig=/etc/kubernetes/admin.conf
      --namespace=kube-system
      etcd-{{ groups['master'][0] }} --
        etcdctl
        --ca-file /etc/kubernetes/pki/etcd/ca.crt
        --cert-file /etc/kubernetes/pki/etcd/peer.crt
        --key-file /etc/kubernetes/pki/etcd/peer.key
        --endpoints=https://{{ hostvars[groups['master'][0]]['ansible_' + kubernetes_interface].ipv4.address }}:2379
        member add {{ inventory_hostname }} https://{{ hostvars[inventory_hostname]['ansible_' + kubernetes_interface].ipv4.address }}:2380
  ignore_errors: yes

- name: "etcd : local"
  command: /usr/bin/kubeadm alpha phase etcd local --config /tmp/kubeadm-config.yml

- name: "kubeadm : kubeconfig all"
  command: /usr/bin/kubeadm alpha phase kubeconfig all --config /tmp/kubeadm-config.yml

- name: "kubeadm : controlplane all"
  command: /usr/bin/kubeadm alpha phase controlplane all --config /tmp/kubeadm-config.yml

- name: "kubeadm : mark-master"
  command: /usr/bin/kubeadm alpha phase mark-master --config /tmp/kubeadm-config.yml

- name: "kubeadm : clean up"
  file:
    dest: /tmp/kubeadm-config.yml
    state: absent
