---
- name: join masters
  command: >
    /usr/bin/kubeadm join
      --token={{ hostvars[groups['masters'][0]].kubeadm_token }}
      --discovery-token-ca-cert-hash={{ hostvars[groups['masters'][0]].kubeadm_certificate_hash }}
      --control-plane
      --certificate-key={{ hostvars[groups['masters'][0]].kubeadm_certificate_key }}
      {{ kubernetes_load_balancer }}:6443

- name: "kubectl : allow users to read configuration"
  file:
    path: /etc/kubernetes/admin.conf
    mode: 0644

- name: "kubectl : setup environment"
  copy:
    src: kubernetes.sh
    dest: /etc/profile.d/kubernetes.sh

- name: "node : remove master taint"
  command: >
    /usr/bin/kubectl --kubeconfig=/etc/kubernetes/admin.conf
      taint nodes
      {{ inventory_hostname }}
      node-role.kubernetes.io/master-
