---
- include_role:
    name: kubernetes/get-nodes
  when: (inventory_hostname == groups['kubernetes-masters'][0])

- include_tasks: create-token.yml
  when: (inventory_hostname == groups['kubernetes-masters'][0])

- include_tasks: upload-certs.yml
  when: (inventory_hostname == groups['kubernetes-masters'][0])

- include_tasks: join-masters.yml
  when: (inventory_hostname in groups['kubernetes-masters'])
        and not(inventory_hostname in hostvars[groups['kubernetes-masters'][0]].kubernetes_nodes)
        and not(inventory_hostname == groups['kubernetes-masters'][0])

- include_tasks: join-workers.yml
  when: (inventory_hostname in groups['kubernetes-workers'])
        and not(inventory_hostname in hostvars[groups['kubernetes-masters'][0]].kubernetes_nodes)

- include_tasks: delete-token.yml
  when: (inventory_hostname == groups['kubernetes-masters'][0])
