---
- name: join nodes
  command: >
    /usr/bin/kubeadm join
      --token={{ hostvars[groups['masters'][0]].kubeadm_token }}
      --discovery-token-ca-cert-hash={{ hostvars[groups['masters'][0]].kubeadm_certificate_hash }}
      {{ kubernetes_load_balancer }}:6443
