---
# ------------------------------------------------------------------------------
- name: download binary
  unarchive:
    src: https://releases.hashicorp.com/nomad/0.5.6/nomad_0.5.6_linux_amd64.zip
    dest: /usr/bin
    remote_src: True
    validate_certs: False
    owner: root
    group: root
    mode: 0755
