---
- name: ensure target directory is created
  file:
    state: directory
    path: "/etc/docker/certs.d/{{ docker_add_registry_certificate.url }}{%- if docker_add_registry_certificate.port is defined -%}:{{ docker_add_registry_certificate.port }}{%- endif -%}/"

- name: copy certificate
  copy:
    src: "{{ docker_add_registry_certificate.path }}/"
    dest: "/etc/docker/certs.d/{{ docker_add_registry_certificate.url }}{%- if docker_add_registry_certificate.port is defined -%}:{{ docker_add_registry_certificate.port }}{%- endif -%}/"
