---
# ------------------------------------------------------------------------------
- name: install
  yum:
    name: chrony
    state: present

- name: enable and start
  service:
    name: chronyd.service
    state: started
    enabled: yes
