---
# ------------------------------------------------------------------------------
- name: install
  yum:
    name: chrony
    state: latest

- name: enable and start
  service:
    name: chronyd.service
    state: running
    enabled: yes
