---
# ------------------------------------------------------------------------------
- name: start
  command: "docker run --detach=true --net=weave --name rti-perftest-pub guther/rti-perftest -pub -numSubscribers {{ play_hosts | length }} -sleep 1000"
...
