---
- name: apply template
  template:
    src: "{{ create_from_file_src }}"
    dest: "/tmp/{{ create_from_file_dest }}"

- name: kubectl create from file
  command: >
    /usr/bin/kubectl --kubeconfig=/etc/kubernetes/admin.conf
    create
    -f /tmp/{{ create_from_file_dest }}

- name: clean up
  file:
    dest: "/tmp/{{ create_from_file_dest }}"
    state: absent
