---
- name: "ensure directories are created"
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - /etc/kubernetes/pki/etcd
  when: inventory_hostname != groups['master'][0]

- name: "copy : certificates : etcd"
  synchronize:
    src: "/etc/kubernetes/pki/etcd/{{ item }}"
    dest: "/etc/kubernetes/pki/etcd/{{ item }}"
  with_items:
    - ca.crt
    - ca.key
  when: inventory_hostname != groups['master'][0]
  delegate_to: "{{ groups['master'][0] }}"
