---
# ------------------------------------------------------------------------------
- name: install
  yum:
    name: cockpit
    state: latest

- name: enable and start
  service:
    name: cockpit.socket
    state: running
    enabled: yes

# ------------------------------------------------------------------------------
- name: check firewalld status
  command: systemctl status firewalld
  register: service_firewalld_status
  failed_when: "service_firewalld_status.rc > 3"

- name: add firewall rules
  firewalld:
    service: cockpit
    zone: public
    state: enabled
    permanent: true
  when: service_firewalld_status.rc == 0
...
